DATA:
  dataset: vocaset
  data_root: ./vocaset/
  wav_path: wav
  vertices_path: vertices_npy

  # ↓↓↓ pklファイルは排除し、FLAME_sample.ply を1つ読む
  template_file: FLAME_sample.ply

  # stage2(音声→モーション)では音声を使う
  read_audio: True

  # 単一スタイルだけ使う例
  train_subjects: S0
  val_subjects: 
  test_subjects: 

LOSS:
  loss: MSE
  motion_weight: 1.0
  reg_weight: 1.0

NETWORK:
  arch: stage2
  in_dim: 15069
  hidden_size: 1024
  num_hidden_layers: 6
  num_attention_heads: 8
  intermediate_size: 1536
  window_size: 1
  quant_factor: 0
  face_quan_num: 16
  neg: 0.2
  autoencoder: stage1_vocaset
  INaffine: False
  style_emb_method: nnemb  # ダミーの1クラス埋め込み用

VQuantizer:
  n_embed: 256
  zquant_dim: 64

PREDICTOR:
  feature_dim: 1024
  vertice_dim: 15069
  device: cuda
  period: 30
  vqvae_pretrained_path: RUN/vocaset/CodeTalker_s1/model/model.pth.tar
  wav2vec2model_path: facebook/wav2vec2-base-960h
  teacher_forcing: True
  num_layers: 6
  n_head: 4

TRAIN:
  use_sgd: False
  sync_bn: False
  train_gpu: [0]
  workers: 4
  batch_size: 1
  batch_size_val: 1
  base_lr: 0.0001
  StepLR: False
  warmup_steps: 1
  adaptive_lr: False
  factor: 0.3
  patience: 3
  threshold: 0.0001
  poly_lr: False
  epochs: 100
  step_size: 100
  gamma: 0.5
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.002
  manual_seed: 131
  print_freq: 10
  save_freq: 1
  save_path:
  weight:
  resume:
  evaluate: True
  eval_freq: 10

Distributed:
  dist_url: tcp://127.0.0.1:6701
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0

TEST:
  test_workers: 0
  test_gpu: [0]
  test_batch_size: 1
  save: True
  model_path:
  save_folder: